name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-auth:${{ github.sha }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/books
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-books:${{ github.sha }}
      - uses: docker/build-push-action@v5
        with:
          context: ./services/api-gateway
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-gateway:${{ github.sha }}
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mern-frontend:${{ github.sha }}
